.TH "_Split" 3 "Mon Oct 1 2012" "Version 0.8.3" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_Split \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kdbprivate.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBalloc\fP"
.br
.ti -1c
.RI "\fBKeySet\fP ** \fBkeysets\fP"
.br
.ti -1c
.RI "\fBBackend\fP ** \fBhandles\fP"
.br
.ti -1c
.RI "\fBKey\fP ** \fBparents\fP"
.br
.ti -1c
.RI "int * \fBsyncbits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The private split structure.
.PP
\fBkdbSet()\fP splits keysets. This structure contains arrays for various information needed to process the keysets afterwards. 
.SH "Field Documentation"
.PP 
.SS "size_t \fB_Split::alloc\fP"How large the arrays are allocated 
.SS "\fBBackend\fP** \fB_Split::handles\fP"The KDB for the keyset 
.SS "\fBKeySet\fP** \fB_Split::keysets\fP"The keysets 
.SS "\fBKey\fP** \fB_Split::parents\fP"The parentkey for the keyset. Is either the mountpoint of the backend or 'user', 'system' for the splitted root backends 
.SS "size_t \fB_Split::size\fP"Number of keysets 
.SS "int* \fB_Split::syncbits\fP"Bits for various options: Bit 0: Is there any key in there which need to be synced? Bit 1: Do we need relative checks? (cascading backend?) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Elektra from the source code.
