.TH "deprecated" 3 "Mon Oct 1 2012" "Version 0.8.3" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- .TH "deprecated" 3 "Mon Oct 1 2012" "Version 0.8.3" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \-  
.IP "\fBGlobal \fBKDB_O_SORT\fP \fP" 1c
dont use 
.PP
.PP
 
.IP "\fBGlobal \fBkeyGetATime\fP(const Key *key) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeyGetCTime\fP(const Key *key) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeyGetGID\fP(const Key *key) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeyGetMode\fP(const Key *key) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeyGetMTime\fP(const Key *key) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeyGetUID\fP(const Key *key) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeySetATime\fP(Key *key, time_t atime) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeySetCTime\fP(Key *key, time_t ctime) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeySetDir\fP(Key *key) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeySetGID\fP(Key *key, gid_t gid) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeySetMode\fP(Key *key, mode_t mode) \fP" 1c
This API is obsolete. It is only a mapping to keySetMeta(key, 'mode', str) which should be prefered.
.PP
.PP
 
.IP "\fBGlobal \fBkeySetMTime\fP(Key *key, time_t mtime) \fP" 1c
This API is obsolete.
.PP
.PP
 
.IP "\fBGlobal \fBkeySetUID\fP(Key *key, uid_t uid) \fP" 1c
This API is obsolete.
.PP

