.TH "err" 3 "Mon Oct 1 2012" "Version 0.8.3" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
err \- .TH "err" 3 "Mon Oct 1 2012" "Version 0.8.3" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
err \-  
.IP "\fBGlobal \fBelektraDocSet\fP(Plugin *handle, KeySet *returned, Key *parentKey) \fP" 1c
In normal execution cases a positive value will be returned. But in some cases you are not able to set keys and have to return -1. If you declare kdbcGetnoError() you are done, but otherwise you have to set the cause of the error. (Will be added with 0.7.1)
.PP

