.TH "todo" 3 "Mon Jun 18 2012" "Version 0.8.2" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- .TH "todo" 3 "Mon Jun 18 2012" "Version 0.8.2" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \-  
.IP "\fBGlobal \fBelektraDocGet\fP(Plugin *handle, KeySet *returned, Key *parentKey) \fP" 1c
needs some updates
.PP
.PP
 
.IP "\fBGlobal \fBkeyClearSync\fP(Key *key) \fP" 1c
Should be done only in \fBkdbGet()\fP part of plugins.
.PP

