.TH "/home/markus/Projekte/Elektra/current/src/ Directory Reference" 3 "Thu Jan 16 2014" "Version 0.8.4" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/markus/Projekte/Elektra/current/src/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBbindings\fP"
.br
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBlibelektra\fP"
.br
.ti -1c
.RI "directory \fBlibloader\fP"
.br
.ti -1c
.RI "directory \fBplugins\fP"
.br
.in -1c
