.TH "/home/markus/Projekte/Elektra/current/src/plugins/doc/ Directory Reference" 3 "Thu Jan 16 2014" "Version 0.8.4" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/markus/Projekte/Elektra/current/src/plugins/doc/ Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBplugins/doc/doc\&.c\fP"
.br
.in -1c
