.TH "kdb::KeyTypeMismatch" 3 "Sat Jan 12 2013" "Version 0.8.4" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdb::KeyTypeMismatch \- 
.PP
Binary or String key mismatch\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyexcept\&.hpp>\fP
.PP
Inherits \fBkdb::Exception\fP\&.
.SH "Detailed Description"
.PP 
Binary or String key mismatch\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Elektra from the source code\&.
