.TH "kdb::Exception" 3 "Sat Jan 12 2013" "Version 0.8.4" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdb::Exception \- 
.PP
Base class for all elektra exceptions\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyexcept\&.hpp>\fP
.PP
Inherits exception\&.
.PP
Inherited by kdb::KDBException, \fBkdb::KeyException\fP, and \fBkdb::KeyTypeMismatch\fP\&.
.SH "Detailed Description"
.PP 
Base class for all elektra exceptions\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Elektra from the source code\&.
