.TH "deprecated" 3 "Sat Dec 21 2013" "Version 0.8.4" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.IP "\fBGlobal \fBKDB_O_SORT\fP \fP" 1c
dont use  
.IP "\fBGlobal \fBkeyGetATime\fP (const Key *key)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeyGetCTime\fP (const Key *key)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeyGetGID\fP (const Key *key)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeyGetMode\fP (const Key *key)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeyGetMTime\fP (const Key *key)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeyGetUID\fP (const Key *key)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeySetATime\fP (Key *key, time_t atime)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeySetCTime\fP (Key *key, time_t ctime)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeySetDir\fP (Key *key)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeySetGID\fP (Key *key, gid_t gid)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeySetMode\fP (Key *key, mode_t mode)\fP" 1c
This API is obsolete\&. It is only a mapping to keySetMeta(key, 'mode', str) which should be prefered\&. 
.IP "\fBGlobal \fBkeySetMTime\fP (Key *key, time_t mtime)\fP" 1c
This API is obsolete\&. 
.IP "\fBGlobal \fBkeySetUID\fP (Key *key, uid_t uid)\fP" 1c
This API is obsolete\&.
.PP

