.TH "kdb::KeyMetaException" 3 "Sat Jan 12 2013" "Version 0.8.4" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdb::KeyMetaException \- 
.PP
The meta\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyexcept\&.hpp>\fP
.PP
Inherits \fBkdb::KeyException\fP\&.
.PP
Inherited by kdb::KeyBadMeta, and kdb::KeyNoSuchMeta\&.
.SH "Detailed Description"
.PP 
The meta\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Elektra from the source code\&.
