.TH "kdb::KeyInvalidName" 3 "Sat Jan 12 2013" "Version 0.8.4" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdb::KeyInvalidName \- 
.PP
The given keyname was invalid\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyexcept\&.hpp>\fP
.PP
Inherits \fBkdb::KeyException\fP\&.
.SH "Detailed Description"
.PP 
The given keyname was invalid\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Elektra from the source code\&.
