.TH "kdb::KeyException" 3 "Sat Jan 12 2013" "Version 0.8.4" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
kdb::KeyException \- 
.PP
Base Class for any exception thrown by keys\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyexcept\&.hpp>\fP
.PP
Inherits \fBkdb::Exception\fP\&.
.PP
Inherited by \fBkdb::KeyInvalidName\fP, and \fBkdb::KeyMetaException\fP\&.
.SH "Detailed Description"
.PP 
Base Class for any exception thrown by keys\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Elektra from the source code\&.
