.TH "_KeySet" 3 "Wed May 9 2012" "Version 0.8.0" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_KeySet \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <kdbprivate.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fB_Key\fP ** \fBarray\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "size_t \fBalloc\fP"
.br
.ti -1c
.RI "struct \fB_Key\fP * \fBcursor\fP"
.br
.ti -1c
.RI "size_t \fBcurrent\fP"
.br
.ti -1c
.RI "ksflag_t \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The private KeySet structure.
.PP
Its internal private attributes should not be accessed directly by regular programs. Use the \fBKeySet access methods\fP instead. Only a backend writer needs to have access to the private attributes of the KeySet object which is defined as: 
.PP
.nf
typedef struct _KeySet KeySet;

.fi
.PP
 
.SH "Field Documentation"
.PP 
.SS "size_t \fB_KeySet::alloc\fP"Allocated size of array 
.SS "struct \fB_Key\fP** \fB_KeySet::array\fP"Array which holds the keys 
.SS "size_t \fB_KeySet::current\fP"Current position of cursor 
.SS "struct \fB_Key\fP* \fB_KeySet::cursor\fP"Internal cursor 
.SS "ksflag_t \fB_KeySet::flags\fP"Some control and internal flags. 
.SS "size_t \fB_KeySet::size\fP"Number of keys contained in the KeySet 

.SH "Author"
.PP 
Generated automatically by Doxygen for Elektra from the source code.
