.TH "todo" 3 "Wed May 9 2012" "Version 0.8.0" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- .TH "todo" 3 "Wed May 9 2012" "Version 0.8.0" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \-  
.IP "\fBGlobal \fBkeyClearSync\fP(Key *key) \fP" 1c
Should be done only in \fBkdbGet()\fP part of plugins.
.PP

