.TH "Internal Datastructure for mountpoints" 3 "Wed May 9 2012" "Version 0.8.0" "Elektra" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Internal Datastructure for mountpoints \- 
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBBackend\fP * \fBelektraTrieLookup\fP (\fBTrie\fP *trie, const \fBKey\fP *key)"
.br
.ti -1c
.RI "int \fBelektraTrieClose\fP (\fBTrie\fP *trie, \fBKey\fP *errorKey)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int elektraTrieClose (\fBTrie\fP * trie, \fBKey\fP * errorKey)"Closes the trie and all opened backends within.
.PP
\fBParameters:\fP
.RS 4
\fItrie\fP the trie to close 
.br
\fIerrorKey\fP the key used to report warnings 
.RE
.PP

.SS "\fBBackend\fP* elektraTrieLookup (\fBTrie\fP * trie, const \fBKey\fP * key)"Lookups a backend inside the trie.
.PP
\fBReturns:\fP
.RS 4
the backend if found 
.PP
0 otherwise 
.RE
.PP
\fBParameters:\fP
.RS 4
\fItrie\fP the trie object to work with 
.br
\fIkey\fP the name of this key will be looked up 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for Elektra from the source code.
